; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:arduino-nesso-n1]
; platform = espressif32
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = arduino_nesso_n1
; board = adafruit_feather_esp32c6
; board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_filters = send_on_enter, time
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ESP32_C6_env
	-D ARDUINO_NESSO_N1
    -D ARDUINO_ARDUINO_NESSO_N1  ; Fixes BMI270.cpp error about LED_BUILTIN
    ; -DLED_BUILTIN=ESP32_INTERNAL_LED  ; this prevent redefine error of LED_BUILTIN
	; FORCE COMPILER TO RECOGNIZE CORE WIRE & SPI HEADERS FOR ALL SUB-LIBRARIES
	-I"${platformio.packages_dir}/framework-arduinoespressif32/libraries/Wire/src"
	-I"${platformio.packages_dir}/framework-arduinoespressif32/libraries/SPI/src"
	; Expose M5GFX headers directly to the Arduino_Nesso_N1 build unit
	-I".pio/libdeps/arduino-nesso-n1/M5GFX/src"
	-I".pio/libdeps/arduino-nesso-n1/M5GFX/src/git_submodules/LovyanGFX/src"
	; Expose BMI270 & BMM150 IMU sensors to the Nesso core library
	-I".pio/libdeps/arduino-nesso-n1/Arduino_BMI270_BMM150/src"
lib_ldf_mode = deep+
lib_deps = 
    SPI
    Wire
	m5stack/M5Unified
	; jgromes/RadioLib@^7.7.1
	arduino-libraries/Arduino_BMI270_BMM150@^1.2.3
    https://github.com/arduino-libraries/Arduino_Nesso_N1@^1.0.0